name: Test

on:
  push:
    branches: 
      - master
    paths:
      - '!**/*.md'
  pull_request:
    branches: 
      - master
    paths:
      - '!**/*.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      - name: Install wasm target
        shell: bash
        run: |
          rustup target add wasm32-wasip1

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Run tests
        run: pnpm run test
        shell: bash